name: Python CI

# Trigger on push and pull_request
on: [push, pull_request]

jobs:
  build:
    # Runner ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # You can change this to your version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    # Run tests with pytest
    - name: Run tests with pytest
      run: |
        pytest
    # Run tests and create a JUnit XML report
    - name: Run tests with pytest
      run: |
        pytest --junitxml=report.xml

    # Step 3: Upload the report file so you can download it later
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: report.xml
      # This 'if: always()' ensures the report uploads even when tests fail
      if: always()