name: Python CI

# Trigger on push and pull_request
on: [push, pull_request]

jobs:
  build:
    # Runner ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # You can change this to your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # Run tests with pytest
    - name: Run tests with pytest
      run: |
        pytest
   
   # Run tests and create an HTML report
    - name: Run tests with pytest
      run: |
        pytest --html=report.html --self-contained-html

    # Upload the HTML report as an Artifact
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: html-test-report
        path: report.html
      if: always()